### PR TITLE
optimise SQL to generate points in graph

### PR DESCRIPTION
**Pull request by NyakudyaA**
* Update the SQL to use ST_SetZ (Requires  PostGIS 3.2 and above)
* Update readme to specify a minimum version of PostgreSQL instance required

### CODE REVIEW

**Comment by mdouchin** [comment]
Sorry for the late message. Shouldn't we check the PostgreSQL and PostGIS version and use the old or newer syntax, instead of "forcing" user to migrate their database to 14 to keep the feature ?

**Comment by NyakudyaA** [comment]
> Sorry for the late message. Shouldn't we check the PostgreSQL and PostGIS version and use the old or newer syntax, instead of "forcing" user to migrate their database to 14 to keep the feature ?

I thought about it but the old SQL was generally unusable at all when generating profiles with distances > 1000 to such an extent that is always timing out.

The speed optimisations are below here
Old Query
old-sql

vs
new SQL
new-sql

B

**Comment by arno974** [comment]
You are right @mdouchin, that might be a good idea to check the postgis version and then selecting one of the sql query.
This will allow users with a older postgis version to still be able to use this extension.
@NyakudyaA, I've never noticed any timeout on my side. But you are right sometimes I had to wait a couple of seconds to get the result. 
@NyakudyaA would you like to add the postgis version check and then selecting one of the query or should I do it ?

**Comment by NyakudyaA** [comment]
@arno974 I am not really a PHP guru, You will probably take less time than me to implement it so you can proceed

**Comment by arno974** [comment]
Ok, I'll do it

**Comment by arno974** [comment]
The branch has been reverted the time for me to add the code that check postgis version prior to integrate the ST_SetZ function.

**Pull request merged**
